name: tpi_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  firebase_core: ^2.3.0
  firebase_auth: ^4.1.5
  cloud_firestore: ^4.1.0
  internet_connection_checker: ^1.0.0+1
  overlay_support: ^2.1.0
  email_validator: ^2.1.17
  flutter_lints: ^2.0.1
  file_picker: ^5.2.3
  firebase_storage: ^11.0.6
  google_sign_in: ^5.4.2
  font_awesome_flutter: ^10.3.0
  provider: ^6.0.4
  flutter_facebook_auth: ^5.0.6
  image_picker: ^0.8.6
  flutter_image_compress: ^1.1.3
  cached_network_image: ^3.2.3
  connectivity_plus: ^3.0.2
  flutter_launcher_icons: ^0.11.0
  rename: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter_icons:
  android: true
  ios: true
  image_path: "img/logo.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "img/logo.jpg"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "img/logo.jpg"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "img/logo.jpg"


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - img/back.jpg
  - img/logo.jpg
  - img/google.jpg
  - img/developer.jpg
  - img/logo.jpg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
